-- DROP DATABASE IF EXISTS test;
-- DROP USER IF EXISTS test;
-- CREATE USER test;
-- CREATE DATABASE test;
-- CREATE EXTENSION postgis;
CREATE SCHEMA IF NOT EXISTS test AUTHORIZATION test;

GRANT ALL PRIVILEGES ON DATABASE test TO test;

CREATE TABLE registerUser (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200)
);

